#version 460 core
#extension GL_NV_gpu_shader5 : enable

struct Camera{
    vec3 pos;
    uint pad;
    vec3 pixel00_loc;
    uint pad2;
    vec3 pixel_delta_u_vec;
    uint pad3;
    vec3 pixel_delta_v_vec;
    uint pad4;
};

// header: 1 bit: isLeaf | 31 bits: childPtr
// childMask: 32 bits higher mask values, 32 bits lower mask values
struct TreeNode{
    uint packedData[3];
};

struct HitInfo{
    bool miss;
    vec3 color;
    vec3 pos;
    vec3 normal;
};

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout (binding = 0, rgba32f) uniform image2D imgOutput;

layout(binding = 1, std430) readonly buffer camera_ssbo {
    Camera cam;
};
layout(binding = 2, std430) readonly buffer nodes_ssbo {
    TreeNode nodes[];
};
layout(binding = 3, std430) readonly buffer leafs_ssbo {
   uint8_t leafData[];  
};

layout (binding = 4) uniform sampler2D palette;

layout (location = 0) uniform int MAX_STEPS;
layout (location = 1) uniform vec3 light_direction;
layout (location = 2) uniform uint biggest_level_size;

// Node Helpers
bool nodeIsLeaf(TreeNode n){
    return (n.packedData[0] & 1u) != 0u;
}

uint getNodeChildPtr(TreeNode n){
    return n.packedData[0] >> 1u;
}

uint64_t getNodeChildMask(TreeNode n){
    return uint64_t(n.packedData[1]) | (uint64_t(n.packedData[2]) << 32);
}

// returns index of positions associated child node at this level
// pos is in range [1.0, 2.0)
// with each level more child nodes exists so more mantissa bits are included in cellPos
int getNodeCellIndex(vec3 pos, int scaleExp){
    uvec3 cellPos = floatBitsToUint(pos) >> scaleExp & 3;
    return int(cellPos.x + cellPos.z * 4 + cellPos.y * 16);
}

vec3 floorScale(vec3 pos, int scaleExp){
    uint mask = ~0u << scaleExp;
        return intBitsToFloat(ivec3(floatBitsToInt(pos)) & ivec3(mask)); // erase bits lower than scale
}

void getPrimaryRay(ivec2 screenPos, out vec3 rayPos, out vec3 rayDir){
    vec3 pixel_center = cam.pixel00_loc + (screenPos.x * cam.pixel_delta_u_vec) +
    (screenPos.y * cam.pixel_delta_v_vec);

    rayDir = normalize(pixel_center - cam.pos);
    rayPos = cam.pos;
}

uint popcnt_var64(uint64_t mask, uint width){
    uint himask = uint(mask);
    uint count = 0;

    if (width >= 32) {
        count = bitCount(himask);
        himask = uint(mask >> 32);
    }

    uint m = 1u << (width & 31u);
    count += bitCount(himask & (m - 1u));
    return count;
}

// reverses "pos" from range [1.0, 2.0) to (2.0, 1.0] if "dir > 0"
// all positive values of pos are flipped to their negative equivalent
vec3 getMirroredPos(vec3 pos, vec3 dir, bool rangeCheck){
    vec3 mirrored = uintBitsToFloat(floatBitsToUint(pos) ^ 0x7FFFFFu);

    if (rangeCheck && any(lessThan(pos, vec3(1.0)) || greaterThanEqual(pos, vec3(2.0)))){
        mirrored = 3.0 - pos;
    }

    return vec3(
        dir.x > 0.0 ? mirrored.x : pos.x,
        dir.y > 0.0 ? mirrored.y : pos.y,
        dir.z > 0.0 ? mirrored.z : pos.z
    );
}

bool isSolidVoxelAt(ivec3 voxelPos){
    return voxelPos == ivec3(0.0);
}

// Raycasting
HitInfo castRay(ivec3 worldOffset, vec3 rayPos, vec3 dir){
    float voxelScale = 1.0 / (1 << biggest_level_size); // e.g. 1 << 8 = 256 | maps volume coordinates into [0, 1) range
    vec3 origin = worldOffset * voxelScale + rayPos * voxelScale + 1.0; // maps ray origin into volume's coordinate range. Lands outside of [1, 2) if ray origin not within volume

    // mark ray direction's positive components in a mask
    // 2 bits per directions
    // y00 z00 x00
    uint mirrorMask = 0;
    if (dir.x > 0) mirrorMask |= 3 << 0;
    if (dir.y > 0) mirrorMask |= 3 << 4;
    if (dir.z > 0) mirrorMask |= 3 << 2;

    origin = getMirroredPos(origin, dir, true);

    vec3 invDir = 1.0 / -abs(dir);

    vec3 tEntry = (vec3(1.0) - origin) * invDir;
    vec3 tExit = (vec3(2.0) - origin) * invDir;
    float tMin = max(max(min(tEntry.x, tExit.x), min(tEntry.y, tExit.y)), min(tEntry.z, tExit.z));
    float tMax = min(min(max(tEntry.x, tExit.x), max(tEntry.y, tExit.y)), max(tEntry.z, tExit.z));

    // which side of the AABB does the ray enter the model?
    bvec3 entryMask = bvec3(
        tEntry.x == tMin,
        tEntry.y == tMin,
        tEntry.z == tMin
    );

    HitInfo hit;
    hit.miss = true;

    if (tMin > tMax || tMax < 0.0) return hit;

    // ray position clamped to [1, 2)
    vec3 pos = origin + max(tMin, 0.0) * (-abs(dir));
    pos = clamp(pos, 1.0, 1.99999);

    uint stack[11]; // one idx per level
    int scaleExp = 21;
    
    uint nodeIdx = 0; // root 
    TreeNode node = nodes[nodeIdx];

    vec3 sideDist = vec3(0.0);

    for (int i = 0; i < MAX_STEPS; i++){
        uint childIdx = getNodeCellIndex(pos, scaleExp) ^ mirrorMask;

        // descend if any node exists at position
        while (!nodeIsLeaf(node) && (getNodeChildMask(node) >> childIdx & 1) != 0){
            stack[scaleExp >> 1] = nodeIdx; // save ancestor

            nodeIdx = getNodeChildPtr(node) + popcnt_var64(getNodeChildMask(node), childIdx);
            node = nodes[nodeIdx];

            scaleExp -= 2;
            childIdx = getNodeCellIndex(pos, scaleExp) ^ mirrorMask;
        }

        // stop stepping through volume if leaf with solid voxel has been found
        if (nodeIsLeaf(node) && (getNodeChildMask(node) >> childIdx & 1) != 0) break;

        // otherwise continue stepping in 2³ cuboid steps
        // 0x00330033: OR-sum of all bits in a 2³ cube at zero coordinates in order x + z * 4 + y * 16
        int advScaleExp = scaleExp;
        if ((getNodeChildMask(node) >> (childIdx & 0x2A) & 0x00330033u) == 0u) advScaleExp++;

        vec3 cellMin = floorScale(pos, advScaleExp);
        sideDist = (cellMin - origin) * invDir;
        float tmax = min(min(sideDist.x, sideDist.y), sideDist.z);
        ivec3 maskValue = ivec3((1 << advScaleExp) - 1);
        ivec3 neighborMax = floatBitsToInt(cellMin) + ivec3(
            sideDist.x == tmax ? -1 : maskValue.x,
            sideDist.y == tmax ? -1 : maskValue.y,
            sideDist.z == tmax ? -1 : maskValue.z
        );
        pos = min(origin - abs(dir) * tmax, intBitsToFloat(neighborMax));

        uvec3 diffPos = floatBitsToUint(pos) ^ floatBitsToUint(cellMin);
        int diffExp = findMSB((diffPos.x | diffPos.y | diffPos.z) & 0xFFAAAAAAu);

        if (diffExp > scaleExp){
            scaleExp = diffExp;

            if (diffExp > 21) break;

            nodeIdx = stack[scaleExp >> 1];
            node = nodes[nodeIdx];
        }
    }

    if (nodeIsLeaf(node) && scaleExp <= 21){
        pos = getMirroredPos(pos, dir, false);
        uint childIdx = getNodeCellIndex(pos, scaleExp);

        uint colIdx = leafData[getNodeChildPtr(node) + popcnt_var64(getNodeChildMask(node), childIdx)];
        hit.color = texture(palette, vec2(colIdx / 256.0, 0.5)).rgb;
        hit.pos = (pos - 1.0 - worldOffset * voxelScale) * (1 << biggest_level_size);

        float tmax = min(min(sideDist.x, sideDist.y), sideDist.z);
        bvec3 sideMask;
        if (sideDist == vec3(0.0)){
            sideMask = entryMask;
        } else {
            sideMask = greaterThanEqual(vec3(tmax), sideDist);
        }
        hit.normal = vec3(
            sideMask.x ? -sign(dir.x) : 0.0,
            sideMask.y ? -sign(dir.y) : 0.0,
            sideMask.z ? -sign(dir.z) : 0.0
        );

        hit.miss = false;
    }

    return hit;
}

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

    vec3 rayPos, rayDir;
    getPrimaryRay(texelCoord, rayPos, rayDir);
    
    HitInfo hit = castRay(ivec3(0), rayPos, rayDir);

    vec3 albedo;

    if(!hit.miss){
        vec3 col = hit.color;
        vec3 light_col = vec3(1.0f);

        float ambientStrength = 0.5f;
        vec3 ambient = ambientStrength * light_col;

        vec3 norm = normalize(hit.normal);
        vec3 lightDir = normalize(-light_direction);
        float diff = max(dot(norm, lightDir), 0.0);
        vec3 diffuse = diff * light_col;

        albedo = (ambient + diff) * col;
    } else{
        albedo = vec3(0.2);
    }
 
    imageStore(imgOutput, texelCoord, vec4(albedo, 1.0));

}