#version 460 core

#define PI 3.1415926535897932384626433832795
#define PHI 1.61803398874989484820459
#define INFINITY 1.0 / 0.0

struct Ray{
    vec3 origin;
    vec3 direction;
};

struct HitRecord{
    vec3 p;
    vec3 normal;
    vec3 color;
    float t;
    bool front_face;
};

struct Camera{
    vec3 pos;
    uint pad;
    vec3 pixel00_loc;
    uint pad2;
    vec3 pixel_delta_u_vec;
    uint pad3;
    vec3 pixel_delta_v_vec;
    uint pad4;
};

struct Sphere{
    vec3 center;
    float radius;
};

struct VoxelData{
    uint four_voxels;
};

struct VoxelModel{
    vec3 position_offset;
    uint bit_offset;
    ivec3 size;
    uint padding;
};

layout (local_size_x = 10, local_size_y = 10, local_size_z = 1) in;
layout (binding = 0, rgba32f) uniform image2D imgOutput;

layout(binding = 1, std430) readonly buffer camera_ssbo {
    Camera cam;
};

layout (binding = 2, std430) readonly buffer voxel_grid_ssbo {
    VoxelData grid[];
};

layout (binding = 3, std430) readonly buffer voxel_model_ssbo {
    VoxelModel models[];
};

layout (binding = 4) uniform sampler2D palette;

layout (location = 0) uniform float t; // Time
layout (location = 1) uniform int model_array_size;
layout (location = 2) uniform int MAX_STEPS;
layout (location = 3) uniform vec3 light_direction;

float ray_tmax = INFINITY;
float ray_tmin = 0.0;

float seed = 42;

// hash-based random function
float random_float(vec2 st) {
    return fract(tan(distance(st*PHI, st) * seed)*st.x);
}

// Returns random float in [0,1)
float random_float(vec2 seed, float offset) {
    return random_float(seed + vec2(offset, offset));
}

// Returns random float in [min,max)
float random_float_range(vec2 seed, float offset, float minVal, float maxVal) {
    return minVal + (maxVal - minVal) * random_float(seed, offset);
}

// Returns a random vec3 in [0,1)
vec3 random_vec3(vec2 seed) {
    return vec3(
        random_float(seed, 0.0),
        random_float(seed, 1.0),
        random_float(seed, 2.0)
    );
}

// Returns a random vec3 in [min,max)
vec3 random_vec3_range(vec2 seed, float minVal, float maxVal) {
    return mix(vec3(minVal), vec3(maxVal), random_vec3(seed));
}

vec3 random_unit_vector(vec2 seed) {
    float u = random_float(seed + vec2(0.0, 1.0));
    float v = random_float(seed + vec2(2.0, 3.0));

    float theta = 2.0 * PI * u;
    float z = 2.0 * v - 1.0;
    float r = sqrt(1.0 - z*z);

    return vec3(r * cos(theta), r * sin(theta), z);
}

vec3 random_on_hemisphere(vec2 seed, vec3 normal) {
    vec3 on_unit_sphere = random_unit_vector(seed);
    if (dot(on_unit_sphere, normal) > 0.0)
        return on_unit_sphere;
    else
        return -on_unit_sphere;
}


vec3 point_at(Ray ray, float t){
    return ray.origin + t * ray.direction;
}

void set_face_normal(inout HitRecord rec, const Ray r, vec3 outward_normal){
    rec.front_face = dot(r.direction, outward_normal) < 0;
    rec.normal = rec.front_face ? outward_normal : -outward_normal;
}

float ray_aabb(const vec3 grid_min, const vec3 grid_max, const Ray r, float ray_tmin, float ray_tmax, out int entry_axis){
    entry_axis = -1;
    for (int axis = 0; axis < 3; ++axis){ // x y z axis
        const float t1 = (grid_min[axis] - r.origin[axis]) / r.direction[axis];
        const float t2 = (grid_max[axis] - r.origin[axis]) / r.direction[axis];

        const float dmin = min(t1, t2);
        const float dmax = max(t1, t2);

        if (dmin > ray_tmin){
            ray_tmin = dmin;
            entry_axis = axis;
        }

        ray_tmax = min(dmax, ray_tmax);

        if (ray_tmax < ray_tmin) return INFINITY;
    }

    return ray_tmin;
}

bool find_nearest(Ray r, VoxelModel model, float ray_tmin, float ray_tmax, out HitRecord rec){
    ivec3 model_size = model.size;
    vec3 grid_min = model.position_offset.yzx - floor(model_size.yzx / 2.0);
    vec3 grid_max = grid_min + model_size.yzx;
    
    int entry_axis;
    const float entry_t = ray_aabb(grid_min, grid_max, r, ray_tmin, ray_tmax, entry_axis); // tmin of aabb

    if (entry_t == INFINITY) return false; // no hit

    vec3 voxels_per_unit;
    voxels_per_unit.x = model_size.y / (grid_max.x - grid_min.x);
    voxels_per_unit.y = model_size.z / (grid_max.y - grid_min.y);
    voxels_per_unit.z = model_size.x / (grid_max.z - grid_min.z);

    const vec3 entry_pos = ((r.origin + r.direction * (entry_t + 0.001)) - grid_min) * voxels_per_unit;

    const vec3 step = sign(r.direction);
    const vec3 delta = abs(1.0 / r.direction);

    // position clamped to model size
    vec3 pos;
    pos.x = clamp(floor(entry_pos.x), 0, model_size.y);
    pos.y = clamp(floor(entry_pos.y), 0, model_size.z); 
    pos.z = clamp(floor(entry_pos.z), 0, model_size.x); 

    vec3 tmax;
    for (int i = 0; i < 3; i++) {
        if (r.direction[i] > 0.0) {
            tmax[i] = (floor(entry_pos[i]) + 1.0 - entry_pos[i]) * delta[i];
        } else {
            tmax[i] = (entry_pos[i] - floor(entry_pos[i])) * delta[i];
        }
    }


    int axis = 0;
    for (int steps = 0; steps < MAX_STEPS; ++steps){
         const int voxel_index = int(pos.y) * model_size.x * model_size.y + int(pos.x) * model_size.x + int(pos.z);

        uint base_offset = uint(model.bit_offset);   // in bytes / uint8_t
        uint word_index  = base_offset / 4; // uint32_t floored
        uint byte_index  = base_offset % 4; // amount of uint8_t's missing from word_index

        uint voxel_byte  = voxel_index + byte_index;
        uint word        = (voxel_byte / 4) + word_index;
        uint shift       = 8 * (voxel_byte % 4);

        VoxelData voxel_data = grid[word];
        uint col_idx = (voxel_data.four_voxels >> shift) & 255;


        if (bool(col_idx)) {
            if (steps == 0) {
                rec.t = entry_t;
                rec.p = r.origin + rec.t * r.direction;

                // normal from AABB entry face
                vec3 outward_normal = vec3(0.0);
                outward_normal[entry_axis] = -sign(r.direction[entry_axis]);
                set_face_normal(rec, r, outward_normal);
            } else {
                rec.t = entry_t + tmax[axis] - delta[axis];
                rec.p = r.origin + rec.t * r.direction;

                // normal from voxel boundary crossing
                vec3 outward_normal = vec3(0.0);
                outward_normal[axis] = -step[axis];
                set_face_normal(rec, r, outward_normal);
            }

            rec.color = texture(palette, vec2(col_idx / 256.0, 0.5)).rgb;
            return true;
        }

        if (tmax.x < tmax.y) {
            if (tmax.x < tmax.z) {
                pos.x += step.x;
                if (pos.x < 0 || pos.x >= model_size.y) break;
                axis = 0;
                tmax.x += delta.x;
            } else {
                pos.z += step.z;
                if (pos.z < 0 || pos.z >= model_size.x) break;
                axis = 2;
                tmax.z += delta.z;
            }
        } else {
            if (tmax.y < tmax.z) {
                pos.y += step.y;
                if (pos.y < 0 || pos.y >= model_size.z) break;
                axis = 1;
                tmax.y += delta.y;
            } else {
                pos.z += step.z;
                if (pos.z < 0 || pos.z >= model_size.x) break;
                axis = 2;
                tmax.z += delta.z;
            }
        }
    }

    return false;
}

bool hit_sphere(const Sphere s, const Ray r, float ray_tmin, float ray_tmax, out HitRecord rec){
    vec3 oc = s.center - r.origin;
    float a = dot(r.direction, r.direction);
    float h = dot(r.direction, oc);
    float c = dot(oc, oc) - s.radius * s.radius;

    float discriminant = h * h - a * c;
    if (discriminant < 0){
        return false;
    }

    float sqrtd = sqrt(discriminant);

    float root = (h - sqrtd) / a;
    // surrounds
    if (root <= ray_tmin || ray_tmax <= root){
        root = (h + sqrtd) / a;
        // surrounds
        if (root <= ray_tmin || ray_tmax <= root)
            return false;
    }

    rec.t = root;
    rec.p = point_at(r, rec.t);
    vec3 outward_normal = (rec.p - s.center) / s.radius;
    set_face_normal(rec, r, outward_normal);
    return true;
}

bool hit_coordinate_spheres(Ray r, float ray_tmin, float ray_tmax, out vec3 color){
    HitRecord rec;
    float closest_so_far = ray_tmax;
    bool hit_anything = false;

    Sphere scene_center, sphere_x, sphere_y, sphere_z;
    scene_center.center = vec3(0.0);
    sphere_x.center = vec3(10.0, 0.0, 0.0);
    sphere_y.center = vec3(0.0, 10.0, 0.0);
    sphere_z.center = vec3(0.0, 0.0, 10.0);
    scene_center.radius = 1.0;
    sphere_x.radius = 1.0;
    sphere_y.radius = 1.0;
    sphere_z.radius = 1.0;

    Sphere spheres[4] = {scene_center, sphere_x, sphere_y, sphere_z};

    HitRecord sphere_rec;
    for (int i = 0; i < 4; i++){
        Sphere s = spheres[i];
        bool hit = hit_sphere(s, r, ray_tmin, closest_so_far, sphere_rec);
        if (hit){
            hit_anything = true;
            closest_so_far = sphere_rec.t;
            rec = sphere_rec;
            rec.color = s.center / 10;
        }
    }

    if (hit_anything){
        color = rec.color;
        return true;
    }

    return false;
}

vec3 ray_color(Ray r){
    // coordinate spheres
    vec3 sphere_color;
    if (hit_coordinate_spheres(r, ray_tmin, ray_tmax, sphere_color))
        return sphere_color;

    HitRecord rec;
    bool hit_anything = false;
    float closest_so_far = ray_tmax;

    for (int i = 0; i < model_array_size; i++){
        HitRecord voxel_rec;
        if (find_nearest(r, models[i], ray_tmin, closest_so_far, voxel_rec)){
            if (voxel_rec.t < closest_so_far){
                closest_so_far = voxel_rec.t;
                rec = voxel_rec;
                hit_anything = true;
            }
        }
    }

    if (hit_anything) {
        vec3 col = rec.color;
        vec3 light_col = vec3(1.0f);

        float ambientStrength = 0.5f;
        vec3 ambient = ambientStrength * light_col;

        vec3 norm = normalize(rec.normal);
        vec3 lightDir = normalize(-light_direction);
        float diff = max(dot(norm, lightDir), 0.0);
        vec3 diffuse = diff * light_col;

        return (ambient + diff) * col;
    }
        
    return vec3(0.2);
}

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

    vec3 pixel_color = vec3(0.0);

    vec3 pixel_center = cam.pixel00_loc + (texelCoord.x * cam.pixel_delta_u_vec) +
    (texelCoord.y * cam.pixel_delta_v_vec);

    vec3 ray_direction = normalize(pixel_center - cam.pos);
    
    Ray r = Ray(cam.pos, ray_direction);

    pixel_color = ray_color(r);
 
    imageStore(imgOutput, texelCoord, vec4(pixel_color, 1.0));

}